apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  # change keycloak.default.svc.cluster.local to keycloak public ip
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: "http://k8s-dlorg-6cc494f133-886732042.us-east-1.elb.amazonaws.com/auth/realms/spring-microservices-security-realm"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak.default.svc.cluster.local:8080/realms/spring-microservices-security-realm/protocol/openid-connect/certs"